language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

# remove after guzzle 5.3.1 https://github.com/guzzle/guzzle/issues/1269
matrix:
  allow_failures:
    - php: nightly

install:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

before_script:
  - phpenv config-rm xdebug.ini || return 0

script:
  - phpunit --verbose
  - bin/php-cs-fixer --diff --dry-run -v fix
