language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'

matrix:
  include:
    - php: '7.0'
      dist: trusty
    - php: '7.1'
      dist: trusty
    - php: nightly
      dist: trusty
    - php: hhvm
      dist: trusty

install:
  - composer self-update
  - composer install --no-interaction --prefer-source

before_script:
  - phpenv config-rm xdebug.ini || return 0

script:
  - bin/phpunit --verbose
  - bin/php-cs-fixer --diff --dry-run -v fix
