language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

install:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

before_script:
  - phpenv config-rm xdebug.ini

script:
  - phpunit --verbose
  - php php-cs-fixer --diff --dry-run -v fix
